global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        #chroot /home/haproxy
        #uid 508
        #gid 508
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option  forwardfor
        retries 3
        option  redispatch
        maxconn 2000
        contimeout      5000
        clitimeout      50000
        srvtimeout      50000
        stats enable

listen stats :8888
        mode http
        balance source
        stats uri /

